name: CI Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandoc
    - name: Export documents
      run: |
        python3 export.py --format csv
        python3 export.py --format json
        python3 export.py --format xml
    - name: Generate document
      run: |
        chmod +x generate-document.sh
        ./generate-document.sh
